#!/usr/bin/env python
import os,sys
path=os.path.abspath(os.path.split(sys.argv[0])[0]);
os.environ["LD_LIBRARY_PATH"]=path;
os.execv(path+"/cppsp_standalone",[path+"/cppsp_standalone","-c","-fPIC","-c","-I"+path+"/include","-c","-L"+path,"-c","-lpthread","-c","-lcpoll","-c","-lcppsp"]+sys.argv[1:]);

